apiVersion: v1
kind: Pod
metadata:
  name: agent-pod
spec:
  containers:
  - name: agent-container
    image: yoonseongduk/agent:latest
    env:
    - name: MASTER_SERVICE_HOST
      value: "master-service"
