# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\" \n\rMasterRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eMasterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\rMasterService\x12.\n\x0bGetResponse\x12\x0e.MasterRequest\x1a\x0f.MasterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MASTERREQUEST']._serialized_start=16
  _globals['_MASTERREQUEST']._serialized_end=48
  _globals['_MASTERRESPONSE']._serialized_start=50
  _globals['_MASTERRESPONSE']._serialized_end=83
  _globals['_MASTERSERVICE']._serialized_start=85
  _globals['_MASTERSERVICE']._serialized_end=148
# @@protoc_insertion_point(module_scope)
